trigger:
- main  # Define the branch you want to trigger the CI/CD process

pool:
  vmImage: 'windows-latest'  # Use a Windows agent

steps:
- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet  # Path to install .NET SDK

- script: dotnet build --configuration Release
  displayName: 'Build the project'

- script: |
    cd "C:\Users\Jignesh_Optimum\Development Code\.net Core\PracticeWebApp"
    $env:Solution_Name = "PracticeWebApp.sln"
    $env:Configuration = "Release"
    msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
  displayName: 'Restore NuGet packages'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'  # Directory where the build outputs are located
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/publish.zip'  # Path to the zip file
    replaceExistingArchive: true
  displayName: 'Create zip archive'
