name: Build and Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: |
        dotnet build --no-restore --configuration Debug
        mkdir -p ${{ github.workspace }}/publish_zip/Project1_Debug
        dotnet publish -c Debug -o ${{ github.workspace }}/publish/Project1/PracticeWebApp.csproj ${{ github.workspace }}/publish_zip/Project1_Debug
        mkdir -p ${{ github.workspace }}/publish_zip/Project2_Release
        dotnet publish -c Release -o ${{ github.workspace }}/publish/Project2/PracticeWebApp.csproj ${{ github.workspace }}/publish_zip/Project2_Release

    - name: Package
      run: |
        mkdir -p ${{ github.workspace }}/publish_zip
        zip -r ${{ github.workspace }}/publish_zip/publish.zip ${{ github.workspace }}/publish_zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: publish-artifact
        path: ${{ github.workspace }}/publish_zip/publish.zip
