name: Build and Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: |
        dotnet build --no-restore
        mkdir -p ${{ github.workspace }}/publish
        dotnet publish -c Release -o ${{ github.workspace }}/publish/Project1 PracticeWebApp.csproj
        dotnet publish -c Release -o ${{ github.workspace }}/publish/Project2 PracticeWebApp.csproj

    - name: Package
      run: |
        mkdir -p ${{ github.workspace }}/publish_zip
        zip -r ${{ github.workspace }}/publish_zip/publish.zip ${{ github.workspace }}/publish
