name: Build, test, and package
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter "Category!=LongRunning"

    - name: Package
      run: |
        mkdir publish_zip
        cd <C:\Users\Jignesh_Optimum\Development Code\.net Core\PracticeWebApp\Publish>
        zip -r ../publish_zip/publish.zip .
      working-directory: <path-to-your-project-directory>
